### ISSUE TITLE
Docker HUB stuck on version 7.2.0 as the most recent

### ISSUE THREAD

**Issue by fanaticDavid** [tiredofit/docker-traefik-cloudflare-companion#100]
### Summary

The most recent version of this application on the Docker HUB is 7.2.0

### Steps to reproduce

Look [here](https://hub.docker.com/r/tiredofit/traefik-cloudflare-companion/tags) for the available tags.

### What is the expected *correct* behavior?

To see the tags `7.2.1`, `7.2.2` and `7.3.3` on Docker HUB, as well as the `latest` tag being up-to-date.

**Comment by tiredofit** [comment]
Thanks, Resolved with a commit that was not pushed on my end for the past few months. Builds have been restored..
