### ISSUE TITLE
./run: line 11: exec: python: not found

### ISSUE THREAD

**Issue by modem7** [tiredofit/docker-traefik-cloudflare-companion#14]
Latest tag has error: 

[INFO] ** [traefik-cloudflare-companion] Starting Traefik Cloudflare Companion
./run: line 11: exec: python: not found

4.2.0 and 4.2.1 is absolutely fine.

**Comment by tiredofit** [comment]
Ack, an autobuild must have triggered this.  Looking into.

**Comment by tiredofit** [comment]
I've manually pushed a new `:latest` tag. Something interesting happens with Docker Hub every once in a while that I can't fully put my finger on, where it forgets to download certain packages. I'll review its caching settings. It only seems to happen when I have a big backlog of builds ahead of it. Regardless, thanks for letting me know.

**Comment by modem7** [comment]
All good now!

Cheers for the quick resolve!
