### ISSUE TITLE
Allow records to be updated if they already exist

### ISSUE THREAD

**Issue by dchidell** [tiredofit/docker-traefik-cloudflare-companion#18]
Currently, records that already exist will not be updated. They may need updating if various attributes change (TTL, proxy status, target CNAME).

PR #17 addresses this.

**Comment by tiredofit** [comment]
Hi there, great stuff. I think I'm going to need to test this extensively. This is definitely a desirable set of features. I'll review in the next couple of days as I've just taken in some house guests.

**Comment by tiredofit** [comment]
Update records if they already exist now available in `tiredofit/traefik-cloudflare-companion:5.0.0`
Thank you @dchidell for taking this on.

**Comment by tiredofit** [comment]
Now rewritten as `tiredofit/traefik-cloudflare-companion:6.0.0` in Python3
