### ISSUE TITLE
Support for Raspberry Pi

### ISSUE THREAD

**Issue by rdricco** [tiredofit/docker-traefik-cloudflare-companion#2]
Can you add support for raspberry?

**Comment by jwillmer** [comment]
I have played around with it and created a ARM image. You can use the following image till the author updated the repository.

## ARM image: 

- docker.pkg.github.com/jwillmer/docker-traefik-cloudflare-companion/docker-traefik-cloudflare-companion:6.1.2
- docker.pkg.github.com/jwillmer/docker-alpine/alpine-arm:3.12

## Repositories with the changes:

- https://github.com/jwillmer/docker-traefik-cloudflare-companion
- https://github.com/jwillmer/docker-alpine

## Things I needed to change:

### tiredofit/docker-alpine:3.1.2

- [armhf package for S6 installation](https://github.com/jwillmer/docker-alpine/blob/fb48acfb88847100f691417c9683cf647560ff05/Dockerfile#L108)

### tiredofit/docker-traefik-cloudflare-companion

- [Python installation](https://github.com/jwillmer/docker-traefik-cloudflare-companion/blob/258e616a337c1827aba7db9768ff0841007edae5/Dockerfile#L18-L26):

```
ENV PYTHONUNBUFFERED=1
RUN apk add python3 python3-dev && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
RUN pip install \
        cloudflare \
        get-docker-secret 
RUN pip install docker[tls]
```

**Comment by nearcatch** [comment]
> I have played around with it and created a ARM image. You can use the following image till the author updated the repository.

Spun up a container on my Pi using your package and it worked fine, thanks.

**Comment by zhorvath83** [comment]
@jwillmer I would like to ask your help:
I wanted to pull your CF-Companion ARM docker image `docker.pkg.github.com/jwillmer/docker-traefik-cloudflare-companion/docker-traefik-cloudflare-companion:6.1.2` but I am getting HTTP 404 response constantly.

**Comment by jwillmer** [comment]
@zhorvath83 I don't know why you get this. GitHub does not allow anonymous image downloads. Maybe you are not logged in?

**Comment by tiredofit** [comment]
`tiredofit/traefik-cloudflare-companion:latest` and any tagged version going forward (> `6.4.0` now supports AMD64, ARM7, and AARCH64.
