### ISSUE TITLE
Enchancement: Support for Docker Secrets

### ISSUE THREAD

**Issue by htpcBeginner** [tiredofit/docker-traefik-cloudflare-companion#20]
I moved my CF token to docker secrets from .env. But cf-companion does not appear to work with secrets.

**Comment by tiredofit** [comment]
I have functionality baked into my base images to support docker secrets, just not in this application. It is coming in a future release. Still a few weeks off unfortunately.

**Comment by tiredofit** [comment]
Docker Secrets support now available in `tiredofit/traefik-cloudflare-companion:5.0.0`

**Comment by tiredofit** [comment]
The following above is useful for `tiredofit/traefik-cloudflare-companion:5.0` which I pushed today which I am finding the secrets support questionable.

Instead I just rewrote the whole thing in pure python tagging as `tiredofit/traefik-cloudflare-companion:6.0` 
For this version, You just need to set `CF_EMAIL=None` and don't worry about the `API_MODE` env var, it's been removed. See README.

**Comment by robertbaker** [comment]
I tried using a scoped token that can edit all dns zones. getting auth errors. Secret was loaded into container at /run/secrets/mysecret

**Comment by Tuumke** [comment]
Have same issues..

Whenever i try to use secrets, they just dont work for whatever reason.
Below works:
```
    environment:
      - TIMEZONE=$TZ
      - TRAEFIK_VERSION=2
      - CF_EMAIL=
      - CF_TOKEN=Alkjasdflkj243k76j1#&JLKJa0-24
      - TARGET_DOMAIN=dockers.$DOMAINNAME
      - DOMAIN1=$DOMAINNAME
      - DOMAIN1_ZONE_ID=10654065403241036406504
      - DOMAIN1_PROXIED=TRUE
      - DOCKER_HOST=tcp://socket-proxy:2375
```
This doesnt work:

```
    environment:
      - TIMEZONE=$TZ
      - TRAEFIK_VERSION=2
      - CF_API_TOKEN=/run/secrets/cloudflare_api_token # Scoped api token
      - CF_EMAIL=
      - TARGET_DOMAIN=dockers.tsdev.nl
      - DOMAIN1=$DOMAINNAME
      - DOMAIN1_ZONE_ID=/run/secrets/cloudflare_zoneid # Copy from Cloudflare Overview page
      - DOMAIN1_PROXIED=TRUE
      - DOCKER_HOST=tcp://socket-proxy:2375
    secrets: 
      - cloudflare_email
      - cloudflare_api_token
      - cloudflare_zoneid
```
