### ISSUE TITLE
Support for Traefik V2 labels

### ISSUE THREAD

**Issue by watling777** [tiredofit/docker-traefik-cloudflare-companion#3]
Would it be possible to trigger a CNAME creation/update based on the ``traefik.http.routers.router1.rule=Host(`traefik.example.com`)`` [label](https://docs.traefik.io/routing/routers/#rule)? The `traefik.frontend.rule` label is [not used in version 2 ](https://docs.traefik.io/migration/v1-to-v2/#frontends-and-backends-are-dead-long-live-routers-middlewares-and-services)of Traefik

**Comment by tiredofit** [comment]
Absolutely. I've been using a version privately that supports this and just committed and available on Docker Hub tagged as `4.0` or `latest`.

Make sure you add an environment variable to `TRAEFIK_VERSION=2` for it to work :)

**Comment by watling777** [comment]
Thanks, It works perfect for me!
