### ISSUE TITLE
an A, AAAA or CNAME record already exists with that host

### ISSUE THREAD

**Issue by MaartenKleijwegt** [tiredofit/docker-traefik-cloudflare-companion#37]
Not sure if really a bug but anyway:

I've recently updated my setup to use proxied dns from cloudflare. The first node was done manually. But I hoped to automate the second one a bit by changing the DOMAIN1_PROXIED to TRUE and restarting the container. At first it did nothing (no result and nothing interesting in the logs) but after recreating it through portainer, it spat out the following

```
2020-10-16 08:02:23,553 - Python Cloudflare API v4 - DEBUG - Response: 400, application/json, b'{"result":null,"success":false,"errors":[{"code":81053,"message":"An A, AAAA or CNAME record already exists with that host."}],"messages":[]}'


2020-10-16 08:02:23,553 - Python Cloudflare API v4 - DEBUG - Response: error 81053 An A, AAAA or CNAME record already exists with that host.
```

and:

```
[DEBUG] Container List Discovery Loop


[DEBUG] Called check_container_t2 for: <Container: ca997d9b92>


[DEBUG] Starting event watch routines


--- Logging error ---


Traceback (most recent call last):


  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit


    msg = self.format(record)


  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format


    return fmt.format(record)


  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format


    record.message = record.getMessage()


  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage


    msg = msg % self.args


TypeError: not all arguments converted during string formatting


Call stack:


  File "/usr/sbin/cloudflare-companion", line 253, in <module>


    logger.debug("Time:", t)


Message: 'Time:'


guments: ('1602835343',)


[DEBUG] Called check_container_t2 for: <Container: 2ef775c29e>
```

The first is understandable, The second might be worth looking into.

Also if this is working as intended (might be dangerous to just overwrite existing records, or even impossible with the python API) It might be an idea to include a FORCE_UPDATE_RECORDS parameter for people like me that want all their records updated regardless of current settings

**Comment by tiredofit** [comment]
You can try `REFRESH_ENTRIES=TRUE` to force the entries to be updated each time. Note that this happens each time you start a container or turn one off and walks through all your services. It was added a couple months back but currently FALSE by default.

I'm going to call on @mbjurstrom to have a peek at this since the logging work that was done in the past few weeks was his work.

**Comment by mbjurstrom** [comment]
the second is a easy fix. Was my mistake. Will send a PR in a short while

**Comment by tiredofit** [comment]
Tagged as `tiredofit/traefik-cloudflare-companion:6.3.1`

**Comment by MaartenKleijwegt** [comment]
> You can try `REFRESH_ENTRIES=TRUE` to force the entries to be updated each time. Note that this happens each time you start a container or turn one off and walks through all your services. It was added a couple months back but currently FALSE by default.

I'm very sorry that I didn't notice that before posting. Should have had a better look. Thanks for the pointer
