### ISSUE TITLE
Cloudflare - no CNAME's added

### ISSUE THREAD

**Issue by maxfield-allison** [tiredofit/docker-traefik-cloudflare-companion#4]
I've configured DTCC as described in the example compose file but none of my containers are getting corresponding cnames in cloudflare.
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] 00-functions: applying... 

[fix-attrs.d] 00-functions: exited 0.

[fix-attrs.d] 01-s6: applying... 

[fix-attrs.d] 01-s6: exited 0.

[fix-attrs.d] 02-zabbix: applying... 

[fix-attrs.d] 02-zabbix: exited 0.

[fix-attrs.d] 03-logrotate: applying... 

[fix-attrs.d] 03-logrotate: exited 0.

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] 00-startup: executing... 

[cont-init.d] 00-startup: exited 0.

[cont-init.d] 01-timezone: executing... 

[NOTICE] ** [timezone] Setting timezone to 'America/Chicago'

[cont-init.d] 01-timezone: exited 0.

[cont-init.d] 02-permissions: executing... 

[cont-init.d] 02-permissions: exited 0.

[cont-init.d] 03-zabbix: executing... 

[cont-init.d] 03-zabbix: exited 0.

[cont-init.d] 04-cron: executing... 

[NOTICE] ** [cron] Disabling Cron

[cont-init.d] 04-cron: exited 0.

[cont-init.d] 05-smtp: executing... 

[NOTICE] ** [smtp] Disabling SMTP Features

[cont-init.d] 05-smtp: exited 0.

[cont-init.d] 10-cloudflare-companion: executing... 

/var/run/s6/etc/cont-init.d/10-cloudflare-companion: line 4: prepare_service: command not found

[NOTICE] ** [traefik-cloudflare-companion] Setting Traefik 2.x Mode

[cont-init.d] 10-cloudflare-companion: exited 0.

[cont-init.d] 99-container: executing... 

[cont-init.d] 99-container: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

[INFO] ** [zabbix] Starting Zabbix Agent`

All containers are accessible with wildcard cert.

**Comment by tiredofit** [comment]
There's a problem with the base image right now. I will push a new version right away.

**Comment by maxfield-allison** [comment]
Thanks so much for the speedy reply! I assumed from the log that might be the case. Looking forward to being able to proxy everything through cloudflare!

**Comment by maxfield-allison** [comment]
That did it! Thanks so much! There's one more issue I noted in my testing, I'll go ahead and open a new one for it but it doesn't completely break functionality.
